In [45]:
from google.colab import files
uploaded = files.upload()

Saving BloodPressure.csv to BloodPressure (2).csv

In [46]:
import numpy as np
import pandas as pd
import scipy.stats as stats
df = pd.read_csv('BloodPressure.csv')

In [47]:
dfMale = df.loc[df["sex"] =="Male"]

In [48]:
dfMale

    patient   sex agegrp  bp_before  bp_after
0         1  Male  30-45        143       153
1         2  Male  30-45        163       170
2         3  Male  30-45        153       168
3         4  Male  30-45        153       142
4         5  Male  30-45        146       141
5         6  Male  30-45        150       147
6         7  Male  30-45        148       133
7         8  Male  30-45        153       141
8         9  Male  30-45        153       131
9        10  Male  30-45        158       125
10       11  Male  30-45        149       164
11       12  Male  30-45        173       159
12       13  Male  30-45        165       135
13       14  Male  30-45        145       159
14       15  Male  30-45        143       153
15       16  Male  30-45        152       126
16       17  Male  30-45        141       162
17       18  Male  30-45        176       134
18       19  Male  30-45        143       136
19       20  Male  30-45        162       150
20       21  Male  46-59        149       168
21       22  Male  46-59        156       155
22       23  Male  46-59        151       136
23       24  Male  46-59        159       132
24       25  Male  46-59        164       160
25       26  Male  46-59        154       160
26       27  Male  46-59        152       136
27       28  Male  46-59        142       183
28       29  Male  46-59        162       152
29       30  Male  46-59        155       162
30       31  Male  46-59        175       151
31       32  Male  46-59        184       139
32       33  Male  46-59        167       175
33       34  Male  46-59        148       184
34       35  Male  46-59        170       151
35       36  Male  46-59        159       171
36       37  Male  46-59        149       157
37       38  Male  46-59        140       159
38       39  Male  46-59        185       140
39       40  Male  46-59        160       174
40       41  Male    60+        157       167
41       42  Male    60+        158       158
42       43  Male    60+        162       168
43       44  Male    60+        160       159
44       45  Male    60+        180       153
45       46  Male    60+        155       164
46       47  Male    60+        172       169
47       48  Male    60+        157       148
48       49  Male    60+        171       185
49       50  Male    60+        170       163
50       51  Male    60+        175       146
51       52  Male    60+        175       160
52       53  Male    60+        172       175
53       54  Male    60+        173       163
54       55  Male    60+        170       185
55       56  Male    60+        164       146
56       57  Male    60+        147       176
57       58  Male    60+        154       147
58       59  Male    60+        172       161
59       60  Male    60+        162       164

In [49]:
dfFemale = df.loc[df["sex"] =="Female"]

In [50]:
dfFemale

     patient     sex agegrp  bp_before  bp_after
60        61  Female  30-45        152       149
61        62  Female  30-45        147       142
62        63  Female  30-45        144       146
63        64  Female  30-45        144       138
64        65  Female  30-45        158       131
65        66  Female  30-45        147       145
66        67  Female  30-45        154       134
67        68  Female  30-45        151       135
68        69  Female  30-45        149       131
69        70  Female  30-45        138       135
70        71  Female  30-45        162       133
71        72  Female  30-45        157       135
72        73  Female  30-45        141       168
73        74  Female  30-45        167       144
74        75  Female  30-45        147       147
75        76  Female  30-45        143       151
76        77  Female  30-45        142       149
77        78  Female  30-45        166       147
78        79  Female  30-45        147       149
79        80  Female  30-45        142       135
80        81  Female  46-59        157       127
81        82  Female  46-59        170       150
82        83  Female  46-59        150       138
83        84  Female  46-59        150       147
84        85  Female  46-59        167       157
85        86  Female  46-59        154       146
86        87  Female  46-59        143       148
87        88  Female  46-59        157       136
88        89  Female  46-59        149       146
89        90  Female  46-59        161       132
90        91  Female  46-59        142       145
91        92  Female  46-59        162       132
92        93  Female  46-59        144       157
93        94  Female  46-59        142       140
94        95  Female  46-59        159       137
95        96  Female  46-59        140       154
96        97  Female  46-59        144       169
97        98  Female  46-59        142       145
98        99  Female  46-59        145       137
99       100  Female  46-59        145       143
100      101  Female    60+        168       178
101      102  Female    60+        142       141
102      103  Female    60+        147       149
103      104  Female    60+        148       148
104      105  Female    60+        162       138
105      106  Female    60+        170       143
106      107  Female    60+        173       167
107      108  Female    60+        151       158
108      109  Female    60+        155       152
109      110  Female    60+        163       154
110      111  Female    60+        183       161
111      112  Female    60+        159       143
112      113  Female    60+        148       159
113      114  Female    60+        151       177
114      115  Female    60+        165       142
115      116  Female    60+        152       152
116      117  Female    60+        161       152
117      118  Female    60+        165       174
118      119  Female    60+        149       151
119      120  Female    60+        185       163

In [51]:
dfMale[['bp_before','bp_after']].describe()

        bp_before    bp_after
count   60.000000   60.000000
mean   159.266667  155.516667
std     11.413442   15.243217
min    140.000000  125.000000
25%    150.750000  145.000000
50%    158.000000  158.500000
75%    170.000000  164.750000
max    185.000000  185.000000

In [52]:
dfFemale[['bp_before','bp_after']].describe()

        bp_before    bp_after
count   60.000000   60.000000
mean   153.633333  147.200000
std     10.735600   11.742722
min    138.000000  127.000000
25%    144.750000  138.000000
50%    151.000000  146.000000
75%    161.250000  152.000000
max    185.000000  178.000000

In [53]:
significance = 0.05
stat,p_value = stats.ttest_rel(dfMale['bp_before'], dfMale['bp_after'])

In [54]:
print('t_stat: %0.4f, p_value: %0.4f' % (stat, p_value))
if p_value < significance:
   print ("Reject the null hypothesis")
else:
   print ("Accpet the null hypothesis")

t_stat: 1.5431, p_value: 0.1281
Accpet the null hypothesis

In [55]:
significance = 0.05
stat,p_value = stats.ttest_rel(dfFemale['bp_before'], dfFemale['bp_after'])

In [56]:
print('t_stat: %0.4f, p_value: %0.4f' % (stat, p_value))
if p_value < significance:
   print ("Reject the null hypothesis")
else:
   print ("Accpet the null hypothesis")

t_stat: 3.4767, p_value: 0.0010
Reject the null hypothesis